### ISSUE TITLE
pre-releases for workflow testing, etc.

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#116]
We should cut a pre-release to:
* make sure the release workflow runs smoothly
* kick start the zenodo DOI (see #115)
* allow ample time to troubleshoot the above should they get hinky

I propose we start by bumping the version number in `__init__` down to `v0.0.1` and increment up as needed, then we'll still have `v0.1.0` as the actual release at the end of this month.

**Comment by knaaptime** [comment]
sounds good to me

**Comment by jGaboardi** [comment]
* [ ] cut [`v0.0.2`](https://github.com/pysal/spopt/releases/tag/v0.0.2): success/failure
