### ISSUE TITLE
availability on conda-forge

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#118]
After we make sure the initial release and publish workflow is in order, we need to set up a `spopt-feedstock` so that `spopt` available via `conda-forge`.
* step-by-step instructions [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html)

**Comment by jGaboardi** [comment]
IIRC we need to list at least 2 recipe maintainers (here's [`spaghetti`'s](https://github.com/conda-forge/spaghetti-feedstock#feedstock-maintainers) as an example). I will be one. @xf37 and/or @knaaptime would you also like to be recipe maintainer?

**Comment by knaaptime** [comment]
im happy to do it

**Comment by jGaboardi** [comment]
Started in conda-forge/staged-recipes#13708.

**Comment by jGaboardi** [comment]
We're getting errors in the `staged-recipe`. See [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=265211&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823).

```
Traceback (most recent call last):
  File "/home/conda/staged-recipes/build_artifacts/spopt_1610828040194/test_tmp/run_test.py", line 2, in <module>
    import spopt
  File "/home/conda/staged-recipes/build_artifacts/spopt_1610828040194/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.9/site-packages/spopt/__init__.py", line 4, in <module>
    from .region import MaxPHeuristic
ModuleNotFoundError: No module named 'spopt.region'
```

**Comment by jGaboardi** [comment]
@knaaptime I'm not sure what's going on with the `staged-recipe` failures. Can you take a look if you have some time?

**Comment by knaaptime** [comment]
im equally confused

**Comment by jGaboardi** [comment]
Looks like there is a problem with the build up on PyPI:





```
$ conda create -n spopt_pip python=3.9 ipython pip
$ conda activate spopt_pip
$ conda install geopandas
$ pip install spopt
```
```python
Python 3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:52:42) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import spopt
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-44f6f8e47c0d> in <module>
----> 1 import spopt

~/miniconda3/envs/spopt_pip/lib/python3.9/site-packages/spopt/__init__.py in <module>
      2 
      3 
----> 4 from .region import MaxPHeuristic
      5 from .region import RegionKMeansHeuristic
      6 from .region import Skater

ModuleNotFoundError: No module named 'spopt.region'
```

**Comment by jGaboardi** [comment]
the `staged-recipe` is now [passing](https://github.com/conda-forge/staged-recipes/pull/13708/commits/04dfcd780d97eb6b7a577ba03047150c74fbe76e)

**Comment by knaaptime** [comment]
the recipe was merged on conda-forge, so the recipe should be available in a few hours. This is good to close

**Comment by xf37** [comment]
> IIRC

Sorry to miss this issue. I would also like to be a recipe maintainer. Please add me in. Thanks. @jGaboardi

**Comment by jGaboardi** [comment]
@xf37 You can create a PR for this in [`spopt-feedstock`](https://github.com/conda-forge/spopt-feedstock). You'll need to update two things in [`recipe/meta.yaml`](https://github.com/conda-forge/spopt-feedstock/blob/master/recipe/meta.yaml):
* add your GitHub handle - [here](https://github.com/conda-forge/spopt-feedstock/blob/f52c174c19d675a194fc4f7dec90e991dc17ef85/recipe/meta.yaml#L51)
* bump the build number to 1 - [here](https://github.com/conda-forge/spopt-feedstock/blob/f52c174c19d675a194fc4f7dec90e991dc17ef85/recipe/meta.yaml#L14)

You should wait unit ***after*** the `spopt` `v0.1.0` is up on `conda-forge` to do this. I will make another comment here when that is complete.

**Comment by jGaboardi** [comment]
@xf37 is `spopt v0.1.0` is now up on `conda-forge`.

**Comment by jGaboardi** [comment]
xf37 I took care of this in conda-forge/spopt-feedstock#4.
