### ISSUE TITLE
update travis conventions

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#15]
[update travis CI testing conventions](https://github.com/pysal/spopt/issues/5#issuecomment-524400208) based on guidance from @ocefpaf

@knaaptime

**Comment by jGaboardi** [comment]
PySAL's [`.travis.yml`](https://github.com/pysal/pysal/blob/master/.travis.yml)

**Comment by jGaboardi** [comment]
#16

**Comment by sjsrey** [comment]
We have moved to github actions.
