### ISSUE TITLE
release for meta-package

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#178]
@xf37 @sjsrey @knaaptime Some questions:

* Are there any other pertinent matters to be resolved or included before cutting a summer release to go with the meta release?
* Thoughts on whether this release should be:
  * [x] `v0.1.2`
  * [ ] `v0.2.0`

I will go ahead and rerun the notebooks once we decide on a version and then cut the release.

**Comment by knaaptime** [comment]
iirc (and my cursory look back through the closed issues) we havent added any explicit new *features* since the last release, so i'd personally opt for 0.1.2

**Comment by jGaboardi** [comment]
@knaaptime Yeah, no substantive code changes since last release. Just clean up and improved testing + docs.
