### ISSUE TITLE
new alternative to pulp

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#18]
I just wanted to put this here for a reminder. There is a new(ish) Python solver package that we may condsider: [`coin-or/python-mip`](https://github.com/coin-or/python-mip).

**Comment by jGaboardi** [comment]
Currently `ortools` is the solver listed in [`requirements.txt`](https://github.com/pysal/spopt/blob/master/requirements.txt). This should probably be either swapped back to [`coin-or/pulp`](https://github.com/coin-or/pulp) or changed to `python-mip`. Both the options are "more" open-source and under the [COIN-OR](https://www.coin-or.org) umbrella. In terms of `conda-forge` availability, [`pulp`](https://github.com/conda-forge/pulp-feedstock) is the better option, but I have raised the issue in [`mip`](https://github.com/coin-or/python-mip/issues/56), as well.

**Comment by sjsrey** [comment]
@rwei5 can you let us know your thoughts on this. I think we want to abstract the solver and allow users options to plug into whatever solvers we can support.

**Comment by jGaboardi** [comment]
In terms of the stuff I want to contribution for model building (location allocation, routing, and transportation), having a single dedicated solver would be much less painful. These three types of problems can be seem in the Integrations and Application section of the `spaghetti` [Tutorials](https://pysal.org/spaghetti/tutorials.html).

**Comment by jGaboardi** [comment]
See also #2

**Comment by jGaboardi** [comment]
`mip` was chosen in #49

**Comment by jGaboardi** [comment]
details in #55

**Comment by rwei5** [comment]
We currently used or-tools as our interface to exact solvers because or-tools allow you to use several widely used open-source and commercial solvers in addition to its own coin-or. The new coin-or/pulp James mentioned served as similar purpose. 
I agree with @sjsrey maybe for exact solvers, we do not define any base exact solver and allow people to use whatever exact solver they want as long as they inherit our base class and has the .solve method.

**Comment by jGaboardi** [comment]
> We currently used or-tools as our interface to exact solvers because or-tools allow you to use several widely used open-source and commercial solvers in addition to its own coin-or. The new coin-or/pulp @jGaboardi mentioned served as similar purpose.

During the [`spopt` meeting on 2020-06-05](https://github.com/pysal/spopt/issues/49#issuecomment-639690591) it was decided that we adopt [`coin-or/python-mip`](https://github.com/coin-or/python-mip) for the following reasons:
* `python-mip` is solver agnostic (like [`coin-or/pulp`](https://github.com/coin-or/pulp) and [`google/ortools`](https://github.com/google/or-tools)) and supports both [`coin-or/CBC`](https://github.com/coin-or/Cbc) (open-source) and Gurobi (commercial)
* `CBC` is included with `python-mip`
* Gurobi is by far the most robust and performant commercial solver with potentially dramatic performance improvements compared to Gurobi alone or the Gurobi interfaces in `ortools` and `pulp`
* `ortools` is not available through `conda-forge` and though `python-mip` is not currently available via `conda-forge`, the development team is [aware of the issue](https://github.com/coin-or/python-mip/issues/56)
* `region` only adopted `ortools` as the solver interface since the last release; [previously `pulp` had been used](https://github.com/pysal/region/releases/tag/v0.2.0) and the EOL release for `region` lists `pulp` as a requirement
* `python-mip`'s [syntax is modeled after](https://github.com/coin-or/python-mip#python-mip-mixed-integer-linear-programming-tools) `pulp`

> I agree with @sjsrey maybe for exact solvers, we do not define any base exact solver and allow people to use whatever exact solver they want as long as they inherit our base class and has the .solve method.

The current framework for `spopt`, like `region` before it, does not enforce a specific solver.

If this issue warrants further consideration we should discuss it in the next `spopt` hack and/or the [September dev meeting](https://hackmd.io/lCzJ2zgvTAmjCE6q6Xve3A?both).

**Comment by sjsrey** [comment]
> The current framework for `spopt`, like `region` before it, does not enforce a specific solver.
> 
> If this issue warrants further consideration we should discuss it in the next `spopt` hack and/or the [September dev meeting](https://hackmd.io/lCzJ2zgvTAmjCE6q6Xve3A?both).

There is an spopt meeting this friday at 9am on the pysal calendar.

**Comment by jGaboardi** [comment]
> There is an spopt meeting this friday at 9am on the pysal calendar.

I have started a [meeting notes wiki](https://github.com/pysal/spopt/wiki/Developer-Meeting-Notes) that mimics the one in [`pysal/pysal`](https://github.com/pysal/pysal/wiki/Developer-meetings). The first meeting notes entry is [here](https://hackmd.io/lEQiaEDgSvCjtqUutk8hew).

**Comment by jGaboardi** [comment]
closing for now -- solver agnostic is the way to go -- we just have to make sure the include all necessary solvers/wrappers in the `requirements`, etc.
