### ISSUE TITLE
The dissimilarity parameter should be able to accept a distance/dissimilarity matrix as an alternative to a callable distance function

### ISSUE THREAD

**Issue by Shruthi-Patil** [pysal/spopt#187]
I'm currently working on spatial aggregation of energy systems data. Skater seems interesting for my problem and I would like to try it. 

However, the issue is that my data is 3-dimensional and has a complex structure. I compute the distance between each region pair and generate a matrix containing this info. 

It would be very helpful for my case and many other cases if the dissimilarity could be provided in the form of a pre-computed distance matrix, instead of a distance function.

**Comment by jGaboardi** [comment]
@ljwolf @knaaptime @xf37 Would any of yall be able to look into this?

**Comment by ljwolf** [comment]
Yeah, this should be easy to do. We would need to allow for "dissimilarity='precomputed'", as is common in other sklearn-style estimators. 

As it stands @Shruthi-Patil, you could try using `sklearn.cluster.AgglomerativeClustering()`, which currently supports both [precomputed affinity and connectivity constraints](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html)?

**Comment by Shruthi-Patil** [comment]
@ljwolf I’m currently using the same. The results are okayish. That’s why we’re looking for alternatives. :)

**Comment by ljwolf** [comment]
Interesting.... well I can take a look at customizing this very soon. I think the diff would be about 6 lines.

**Comment by Shruthi-Patil** [comment]
Thanks. I look forward to it 😀

**Comment by jGaboardi** [comment]
@Shruthi-Patil Do you still have any interest in seeing this move forward in #188? If not, we'll go ahead and close it out.

**Comment by Shruthi-Patil** [comment]
@jGaboardi Thanks for the tweaks. However, we went with another algorithm. So please go ahead and close it.
