### ISSUE TITLE
Reference error for Church and Murray book

### ISSUE THREAD

**Issue by qszhao** [pysal/spopt#192]
Hi can you update the reference for Church, R. L., & Murray, A. T. (2018). Location covering models: History, applications and advancements (1st edition 2018). Springer in the facility location modeling jupyter notebook? Now it is written as Location Covering Models - History, Applications, and Advancements - Ronald L. Church, Alan T. Murray. 

Best,
Qunshan

**Comment by jGaboardi** [comment]
See also #190

**Comment by jGaboardi** [comment]
These references are in the `locate` notebooks.
