### ISSUE TITLE
rework JOSS manuscript

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#196]
xref  openjournals/joss-reviews#3330 ([comment](https://github.com/openjournals/joss-reviews/issues/3330#issuecomment-921717815))

We should start thinking about how the revised manuscript will look. @xf37 originally did the draft as a google doc. What do we think about continuing with that? Also, we need to get a release out that includes the `locate` module (prereq #190).

@ljwolf & @qszhao, would you like to get in on the paper, considering your mentorship in GSoC (and Levi's SKATER, SPENC, etc. stuff in `spopt`)?

@gegen07, @sjsrey, @knaaptime, @rwei5

**Comment by qszhao** [comment]
@jGaboardi I would be very happy to help with the manuscript if it is necessary...

**Comment by gegen07** [comment]
For example section for locate module, should we use the real-world dataset or the example dataset using `spaghetti` as written in [readme](https://github.com/pysal/spopt/blob/main/README.md) is enough?
