### ISSUE TITLE
facility location models in a class

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#2]
[As per our meeting this morning](https://github.com/pysal/region/wiki/region-module-reorganization-meeting-notes), here is a [`class I wrote`](https://github.com/jGaboardi/jGaboardi_dissertation/blob/f506c030a98f006885d7be21ad8293d6e0da0da2/code/at1866_Master/optimization_models.py#L21-L747) for my dissertation which uses [`pulp`](https://github.com/coin-or/pulp) for solving four fundamental facility location problems (LSCP, MCLP, PMP, PCP).

pysal/region#18

**Comment by sjsrey** [comment]
I think this would be great to move into [allocate](https://github.com/pysal/spopt/tree/master/spopt/allocate)

**Comment by jGaboardi** [comment]
> I think this would be great to move into [allocate](https://github.com/pysal/spopt/tree/master/spopt/allocate)

[allocate](https://github.com/pysal/spopt/tree/master/spopt/allocate) --> [locate](https://github.com/pysal/spopt/tree/master/spopt/locate)

**Comment by jGaboardi** [comment]
@gegen07 Is currently working in this for GSoC 2021.
