### ISSUE TITLE
Cut release for meta

### ISSUE THREAD

**Issue by gegen07** [pysal/spopt#209]
Cut `spopt` for meta release. @jGaboardi is there any issue to solve before?

**Comment by martinfleis** [comment]
There's nothing to release since the last release, is there? The only commits are related to CI and the JOSS paper, so no change of the codebase. No need to release then.

**Comment by jGaboardi** [comment]
@gegen07, I agree with @martinfleis on this. I was hoping to have our JOSS paper out by now to have in the release, but we'll just have to wait.

**Comment by jGaboardi** [comment]
Closing this. We'll hopefully have more to release by next meta cycle.
