### ISSUE TITLE
differentiating spatial clusterers

### ISSUE THREAD

**Issue by knaaptime** [pysal/spopt#21]
raising for discussion: is it worth being explicit in the API about clustering algos that strictly regionalize (e.g. maxp, skater) vs those that blend geographic and attribute dissimilarities (e.g. spenc, spatial_ward, etc) to get a spatially-encouraged solution? Might we want to put them in separate submodules or something to make it more explicit to the user?

**Comment by sjsrey** [comment]
Let's implement the individual modules first, then think if it makes sense to nest them in different layers across the spatially encouraged vs. explicit dimension.

**Comment by jGaboardi** [comment]
@knaaptime @sjsrey Is this still under consideration / discussion? If so, I am going to move it over into *Discussions*.

**Comment by knaaptime** [comment]
or close, if you prefer.  I dont have a strong opinion about if/how to reorganize

**Comment by jGaboardi** [comment]
OK, Let's go ahead and close for now. We can reopen in the future if the come up again.
