### ISSUE TITLE
MCLP with optional Capacity of Facilities Constraint

### ISSUE THREAD

**Issue by TimMcCauley** [pysal/spopt#222]
One fairly popular problem which we have encountered over the past few months is the maximum coverage problem with an optional additional constraint namely the capacity of facilities. I was wondering if this is something you have been thinking about adding?

**Comment by jGaboardi** [comment]
Yes, we were thinking about implementing that in [last year's GSoC](https://github.com/pysal/pysal/wiki/Google-Summer-of-Code-2021#open-source-facility-location-modeling-spopt-development) (which we didn't have time for), and it's on the list for potential improvements for [this year's GSoC](https://github.com/pysal/pysal/wiki/Google-Summer-of-Code-2022#open-source-facility-location-modeling-spopt-development).

**Comment by TimMcCauley** [comment]
Superb, thanks. I will close this now and leave that [GSoC link here](https://github.com/pysal/pysal/wiki/Google-Summer-of-Code-2022#open-source-facility-location-modeling-spopt-development).
