### ISSUE TITLE
PuLP: cannot execute glpsol.exe when

### ISSUE THREAD

**Issue by bm1961** [pysal/spopt#233]
Hey, 

Sorry I am opening a few issues as I go through the code today.

I am trying to run with my own data:

```
from spopt.locate.coverage import MCLP

mclp = MCLP.from_cost_matrix(
    cost_matrix,
    ai,
    max_coverage=service_dist,
    p_facilities=4,
)

mclp = mclp.solve(pulp.GLPK(msg=False))
```

However this is returning the error:

`---------------------------------------------------------------------------
PulpSolverError                           Traceback (most recent call last)
C:\Users\J84538~1\AppData\Local\Temp\1/ipykernel_21536/516228340.py in <module>
      8 )
      9 
---> 10 mclp = mclp.solve(pulp.GLPK(msg=False))

~\Anaconda3\lib\site-packages\spopt\locate\coverage.py in solve(self, solver)
    579         MCLP object
    580         """
--> 581         self.problem.solve(solver)
    582         return self

~\Anaconda3\lib\site-packages\pulp\pulp.py in solve(self, solver, **kwargs)
   1888         #time it
   1889         self.solutionTime = -clock()
-> 1890         status = solver.actualSolve(self, **kwargs)
   1891         self.solutionTime += clock()
   1892         self.restoreObjective(wasNone, dummyVar)

~\Anaconda3\lib\site-packages\pulp\apis\glpk_api.py in actualSolve(self, lp)
     57         """Solve a well formulated lp problem"""
     58         if not self.executable(self.path):
---> 59             raise PulpSolverError("PuLP: cannot execute "+self.path)
     60         tmpLp, tmpSol = self.create_tmp_files(lp.name, 'lp', 'sol')
     61         lp.writeLP(tmpLp, writeSOS = 0)

PulpSolverError: PuLP: cannot execute glpsol.exe`

Any help appreciated!

Thanks!

**Comment by gegen07** [comment]
@bm1961 Do you have GLPK installed? If so, you can check if it's available for pulp by using this [guide](https://coin-or.github.io/pulp/main/installing_pulp_at_home.html#testing-your-pulp-installation).

**Comment by jGaboardi** [comment]
Closing this as answered. If you still have issues @bm1961, please reopen.
