### ISSUE TITLE
Factoring in Facility Capacities

### ISSUE THREAD

**Issue by jartantupjar** [pysal/spopt#234]
Hi, 

I'm wondering if the library can solve this optimization problem: 
Say I have a 5x5 empty grid and I have **N** facilities each with their own capacity. Eg facility 1 needs 6 blocks and facility 2 needs 12 blocks. I want the model to assign spaces in the grid that meet the capacity requirement and spaces that belong to the same facility are close to each other.

**Comment by qszhao** [comment]
Hi,

Thanks for the message. We have not developed the capacity components in the spopt but that's certainly on our next agenda this summer!

Qunshan

**Comment by jartantupjar** [comment]
Thank you @qszhao. Would you happen to know of an algorithm/tool that could solve this? I know its sort of possible with Pulp/OR but linear optimization cannot handle distances aspect of my problem.

**Comment by qszhao** [comment]
@jartantupjar I believe this problem must be solved? If not can you give a bit better spatial demonstration of the questions then we can have a think...

**Comment by jGaboardi** [comment]
Functionality for considering facility capacities for the LSCP are being #273.

**Comment by jGaboardi** [comment]
Closing as completed (and maybe lack of context / out of scope). We can reopen if needed.
