### ISSUE TITLE
Add coverage report?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#24]
Creating issue for [this comment](https://github.com/pysal/spopt/pull/22#issue-405723456)

> we are generating a [`cov`](https://github.com/pysal/spopt/blob/efe0f6a9606373b199378c2792897c2cb9eecfea/.github/workflows/unittests.yml#L39) report, but not actually checking/comparing/reporting anything from it. If we would like to set up `codecov`, I can do that easily, I will just need admin access to `spopt`.

See example in [`spaghetti`](https://github.com/pysal/spaghetti/blob/3f14ddaa2fe9fe061adbacf17dea6a197dd73f96/.github/workflows/unittests.yml#L35)

@sjsrey

**Comment by sjsrey** [comment]
@jGaboardi you can add now with admin access

**Comment by jGaboardi** [comment]
Addressing in #27

**Comment by knaaptime** [comment]
it occurs to me that as we build out all this infrastructure, we might want to codify some of it in the submodule template?

**Comment by jGaboardi** [comment]
@knaaptime Yes, this has been started in pysal/submodule_template#28
