### ISSUE TITLE
GSoC 2022 Interfaces for Consistent API Design

### ISSUE THREAD

**Issue by tdhoffman** [pysal/spopt#260]
For GSoC 2022, I'm working on designing more consistent interfaces to PySAL's exploratory and inferential statistics classes. My mentors and I are exploring what might need to be done to
1. render confederated packages compatible with the [`scikit-learn` paradigm](https://scikit-learn.org/dev/developers/develop.html), and 
2. develop [R-style Wilkinson formulas](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm) for modeling classes.

To these ends, we're interested in getting feedback on the desirability and feasibility of these changes from package leads and devs. 
- Do you think the `scikit-learn` model would work well for this package? Why or why not?
- Do you see any sources of potential friction between the existing codebase and the `scikit-learn` model?

Excited to hear your input!

**Comment by jGaboardi** [comment]
Closing out since GSoC have completed.
