### ISSUE TITLE
LSCP  Notebook Plots 

### ISSUE THREAD

**Issue by erinrolson** [pysal/spopt#263]
spopt -> notebooks -> lscp.ipynb
cells 19, 20, 21 
`plot_results(lscp_from_cost_matrix, facility_points)` should be `plot_results(lscp_from_cost_matrix, facilities_snapped)` ?

I'm happy to make the amendments and add to my pull request if you agree.

**Comment by gegen07** [comment]
Yeah, just to plot the original observation points. Although the `from_geodataframe` uses the snapped points in the model, I thought to use snap operation only to take the distance between clients and facilities.

I think we can add a plot to show the snapped locations and add a description of the "real" plot to state the differences. Subplots maybe would be a great idea in this case.

**Comment by jGaboardi** [comment]
We give a plot on the location + explanations, so that should be enough (xref #288)
