### ISSUE TITLE
Add .coverage to .gitignore

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#265]
We should add `.coverage` to [`.gitignore`](https://github.com/pysal/spopt/blob/main/.gitignore).

xref #259

**Comment by erinrolson** [comment]
Does it go in the packages section?
https://github.com/pysal/spopt/blob/687924085dfbbe2f489ae9d341495c4cad71bf5b/.gitignore#L12-L26

**Comment by jGaboardi** [comment]
Good question. It can go in any section.
