### ISSUE TITLE
LSCP-B formulation?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#270]
The LSCP-B formulation in the [demo notebook](https://github.com/pysal/spopt/blob/main/notebooks/lscpb.ipynb) does not match the actual implementation we are using within `spopt`. The notebook formulation is coming from (Church & Murray 2018, pg. 60), but the one we are actually using is from (Church & Murray 2008, pg. 225).

* [Church, R. L., & Murray, A. T. (2018). Location covering models: History, applications and advancements (1st edition 2018). Springer](https://www.springer.com/gb/book/9783319998459)

**Comment by jGaboardi** [comment]
@erinrolson

**Comment by erinrolson** [comment]
I created a new branch and redid the formulation [here](https://github.com/erinrolson/spopt/blob/lscpb-formulation/notebooks/lscpb.ipynb).
