### ISSUE TITLE
AttributeError: type object 'FacilityModelBuilder' has no attribute 'add_maximized_min_variable'

### ISSUE THREAD

**Issue by luketankh** [pysal/spopt#278]
Hello, I'm currently doing a simple location planning project, where I want to minimize the euclidean distance between possible facility locations.

The example provided https://github.com/pysal/spopt/blob/main/notebooks/facloc-disperse-real-world.ipynb uses P-Dispersion from spopt/locate.

Initially, when I first came across this problem, I did a pip uninstall and reinstall, using pip install spopt. It did not solve the problem. Afterwards, I manually cloned this repo and moved the spopt folder into my site-packages. However, I am still facing this problem.

Thank you for your advice. This package is one of the coolest packages I've played with.

**Comment by jGaboardi** [comment]
@luketankh Which version of `spopt` are you using? Run the following in your environment:

```python
import spopt
spopt.__version__
```

**Comment by luketankh** [comment]
Hi James,

Apologies for the late email. The error no longer occurs now, it was probably an error on my end.

Really sorry for the mixup. Will close the issue on GitHub. 

Thank you for your cool work! 

With regards,
Luke

**Comment by jGaboardi** [comment]
No, problem! Glad it is resolved.
