### ISSUE TITLE
test `spopt` against the `shapely==2.0b1`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#289]
As per @martinfleis' recommendation, we should test `spopt` against the `shapely` pre-release for future-proofing.

```
# using pip
pip install --pre shapely==2.0b1
# using conda /mamba
conda install -c conda-forge/label/shapely_dev shapely
```

@martinfleis Do you think testing with an environment locally is sufficient or possibly going as far as adding some environments to the testing matrix?

**Comment by martinfleis** [comment]
I would add it to CI.

**Comment by jGaboardi** [comment]
xref https://github.com/pysal/libpysal/pull/482
