### ISSUE TITLE
structural/naming alterations?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#32]
Following up with #2, maybe we should reconsider the structure of `spopt`. The current structure (of non-base classes, etc) is:

* `allocate`
* `region`
* `route`

I propose we change `allocate` to `facility_location` (or `facloc` for shorthand). I intend to add in covering models (*LSCP*, *MCLP*, etc.) and those don't generally fall under "location allocation". Also, I would like to add in a Transportation Problem class, so maybe changing `route` to `transport`, which would house transportation-oriented models, is a good idea. So the new structure would be:

* `facloc`
* `region`
* `transport`

**Comment by ljwolf** [comment]
we should try to avoid abbreviations or portmaneaus in our APIs, I think. 

If `allocate` is too specific, what about just `locate`?

**Comment by jGaboardi** [comment]
> we should try to avoid abbreviations or portmanteaus in our APIs, I think.
> 
> If `allocate` is too specific, what about just `locate`?

I think your suggestion sounds nice.

* `locate`
* `region`
* `transport`

Do you agree with having `transport` house the Transportation Problem, the Traveling Salesperson Problem, etc.? I was trying to think of a good descriptive to:
 * have a clear distinction  from `locate`; and
 * encompass both transportation-style and routing-style problems

Or maybe just stick with `route`?

**Comment by jGaboardi** [comment]
settled on:
* locate
* region
* transport

Will push up new structure soon

**Comment by jGaboardi** [comment]
Addressing in #38
