### ISSUE TITLE
inventory models for consideration

### ISSUE THREAD

**Issue by sjsrey** [pysal/spopt#33]
Review:

- [ ] Geosnap
- [ ] Region
- [ ] Other

Document these lists on the [wiki page](https://github.com/pysal/spopt/wiki/Regionalization-Model-Inventory)

**Comment by sjsrey** [comment]
- Deadline of June 23
- List of potential models to include into region

**Comment by knaaptime** [comment]
https://cran.microsoft.com/web/packages/HiClimR/HiClimR.pdf

**Comment by knaaptime** [comment]
https://arxiv.org/pdf/1707.03897.pdf
