### ISSUE TITLE
`spopt==0.5.0` release

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#331]
We need to cut the next release of `spopt` in the coming week, probably end of next week at the latest. This next release will be `0.5.0`. I would like the following issues addressed and PRs merged before that, if at all possible.
* ***highly desired***
  * [x] #321
     * The PR is up and ready for review – #333 
     * The PR is up and ready for review – #335 
  *  [x] #320
     * The PR is up and ready for review – #329
* ***stretch***
  * [x] #328 
    * The PR is up and ready for review – #336
  * [x] #332

**Comment by jGaboardi** [comment]
This is now ready to go! May start with release candidates to make sure the docs build and release workflow still function as expected.

**Comment by jGaboardi** [comment]
[`spopt==0.5.0rc1`](https://pysal.org/spopt/index.html#) is live. Will wait a couple days to let it filter downstream through `conda-forge` before going forward with `spopt==0.5.0`.

**Comment by knaaptime** [comment]
is that as simple as including a tag with the rc suffix?

**Comment by jGaboardi** [comment]
Yep

```
$ git tag -a v#.#.#rc#
$ git push upstream v#.#.#rc#
```
