### ISSUE TITLE
customize tqdm progress bar in Skater

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#332]
The [`tqdm` progress bar in Skater](https://github.com/pysal/spopt/blob/172b356c444bb1af82d8eb3aefb291976fb3bd61/spopt/region/skater.py#L302) could use some customization to make it less wide. Probably simply changing to `tqdm.auto`, as in [`momepy.graph.py`](https://github.com/pysal/momepy/blob/99cf555f3a8c93356c280ccfc5d13111d0518427/momepy/graph.py#L10), would do the trick.

**Comment by knaaptime** [comment]
not sure if there's a way to control the width, specifically, but i havent really looked. Moving the import from auto will give you the fancy progress bar in a jupyter notebook (*with* ipywidgets) but fallback to the block style if you're in a terminal


also, do we have a test case for when tqdm is not installed? Pretty sure [this line](https://github.com/pysal/spopt/blob/172b356c444bb1af82d8eb3aefb291976fb3bd61/spopt/region/skater.py#L306) will fail cause noop isnt defined and should be pass instead?

**Comment by knaaptime** [comment]
ah, nvm. read too quickly

**Comment by jGaboardi** [comment]
> also, do we have a test case for when tqdm is not installed? Pretty sure [this line](https://github.com/pysal/spopt/blob/172b356c444bb1af82d8eb3aefb291976fb3bd61/spopt/region/skater.py#L306) will fail cause noop isnt defined and should be pass instead?

Recently I added coverage for those lines (see codecov [here](https://app.codecov.io/gh/pysal/spopt/blob/main/spopt/region/skater.py)). I added the [`/.ci/38-MIN.yaml`](https://github.com/pysal/spopt/blob/main/.ci/38-MIN.yaml) specifically without `tqdm` for testing. The `noop` is only defined as a parameter within the context of a stand-in `tqdm` function.

**Comment by knaaptime** [comment]
nice.

yeah i realized shortly it was input to the passthrough function defined just above... i was looking for it to be defined somewhere in the outer function. oops 😛

**Comment by jGaboardi** [comment]
> ah, nvm. read too quickly

... I've never done that before... :speak_no_evil: :joy_cat:
