### ISSUE TITLE
The requirementes notebook is missing from the MANIFEST.in

### ISSUE THREAD

**Issue by ocefpaf** [pysal/spopt#343]
Ping @jGaboardi 

See https://github.com/pysal/spopt/blob/4500eb9c93e8d501dd72ac6eb940d1125c5adee8/MANIFEST.in#L1

**Comment by jGaboardi** [comment]
Thanks for this @ocefpaf. I had not remember that [`requirements_notebooks.txt`](https://github.com/pysal/spopt/blob/main/requirements_notebooks.txt) was added this recently (following the most recent `spopt` release).
