### ISSUE TITLE
PulpSolver Error with lscp_###.solve function

### ISSUE THREAD

**Issue by xf37** [pysal/spopt#356]
I plan to use the lscp.ipynb as a part of lab material in my class. After IT staff successfully installed spopt on desktops in the lab, we got an "PulpSolver Error: cannot execute cbc.exe" every time we ran lscp_###.solve functions. 

After trying multiple ways, I find one way to run successfully as follows:
1, conda uninstall pulp
2, pip install pulp
3, conda install spopt

But still, I am curious about any way to eliminate the errors at the very beginning.

**Comment by qszhao** [comment]
> I plan to use the lscp.ipynb as a part of lab material in my class. After IT staff successfully installed spopt on desktops in the lab, we got an "PulpSolver Error: cannot execute cbc.exe" every time we ran lscp_###.solve functions.
> 
> After trying multiple ways, I find one way to run successfully as follows: 1, conda uninstall pulp 2, pip install pulp 3, conda install spopt
> 
> But still, I am curious about any way to eliminate the errors at the very beginning.

Hi Xin I think we had a previous issue #347. 

Adding a line of code might solve the problem. 
'solver = pl.PULP_CBC_CMD(keepFiles=True)

**Comment by jGaboardi** [comment]
Also: xref #348.

**Comment by xf37** [comment]
> solver = pl.PULP_CBC_CMD(keepFiles=True)

Thanks very much!

**Comment by xf37** [comment]
> 

Got it! Thanks!
