### ISSUE TITLE
Consider using pulp.Binary rather than pulp.Integer as the type for cli_assgn_vars?

### ISSUE THREAD

**Issue by ljwolf** [pysal/spopt#364]
Hi,

On some data I cannot share (sorry!) the P-Median problem solved in CPLEX on Windows is returning assignments that are *nearly* zero or one, but are not quite: 

![index_confusions](https://user-images.githubusercontent.com/2250995/233401787-b825b48d-cf8a-4043-be03-0c1c72bdb710.PNG)

This results in `model.cli2fac` having multiple assignments for some clients, when the P-Median model is supposed to be singly-assigned. We do not yet support partial coverage, and our constraints should prevent this behaviour. To be clear, I think this is CPLEX's problem, not ours. 

At the same time—I know CPLEX is trying its best, but I wonder whether we can help them out by using `pulp.Binary` rather than `pulp.Integer` for binary decision variables? I think this could be done by replacing the `pulp.Integer` types with `pulp.Binary` throughout `FacilityModelBuilder`, and dropping the upper and lower bounds.

**Comment by ljwolf** [comment]
Yes, can try. 

I think, too, we may want to implement a more robust way of constructing `fac2cli` and `cli2fac` in light of these kinds of precision issues... in model instances we know are singly-assigned, maybe we should round `cli_assgn_vars` to an integer when using its values? 

In light of this, I managed to replicate this behaviour with Gurobi in a P-Median on different data by setting the optimality gap to some low number to force early termination at a bad solution. I wonder whether this is more common than we think?

**Comment by jGaboardi** [comment]
Maybe as an order of things to try/implement:
1. @ljwolf's rounding solution
2. See about swapping out integer for binary 
3. manage the logic internally to distinguish between scenarios needing relaxation (capped LSCP) and those that do not (standard PMP instances).

**Comment by jGaboardi** [comment]
Resolved via #366
