### ISSUE TITLE
no demo for k-nearest p-median

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#401]
I just realized we never got a demo into the notebooks for the new $k$-nearest $p$-median functionality. What I am thinking is a new notebook that highlights the differences & similarities in $p$-median variations, all solved with euclidean distance for comparability:
* standard $p$-median
* capacitated $p$-median
* $k$-nearest $p$-median

This should be created and merged prior to the next release (`v0.6.0`), with #386 also being a blocker.

**Comment by qszhao** [comment]
This fits what I can imagine - now the standard and capacitated are blended together. It will be better to have a straightforward comparison and to use the same real-world dataset similar to other coverage notebooks.

**Comment by jGaboardi** [comment]
Following #410/#411, I'd like to put something together for this and cut a `v0.6.0` release this coming week.

**Comment by jGaboardi** [comment]
Resolved via #431
