### ISSUE TITLE
Ideas for topics under the "Manage topics" headline

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#43]
I'll open this issue so we can brainstorm some ideas for topics under the "Manage topics" headline.

**Comment by jGaboardi** [comment]
- [ ] spatial-optimization
- [ ] regionalization
- [ ] facility-location
- [ ] routing
- [ ] transportation
- [ ] spatial analysis
- [ ] python
- [ ] other?

**Comment by jGaboardi** [comment]
@xf37 What do you think about the above topics? Good or no?

**Comment by jGaboardi** [comment]
@sjsrey Do you have any opinions on this?

**Comment by xf37** [comment]
@jGaboardi What are these topics for? To help other people find our project, like keywords for a publication?

**Comment by jGaboardi** [comment]
Good question and sorry for not being clear. Yes, they are for key word search on GitHub. For example, the topics for [`spaghetti`](https://github.com/pysal/spaghetti) are `spatial-network`, `network-analysis`, `python`, etc.

**Comment by jGaboardi** [comment]
I think we should include all the topics from my comment above, but I will wait for your feedback in case you don't agree (and feel free to not agree).

**Comment by xf37** [comment]
@jGaboardi Thanks for the clarification. I think all the topics from your comment are great. I suggest adding location-allocation, location-modeling, resource planning. Let me know your feedback.

**Comment by jGaboardi** [comment]
Those are nice. I will add the terms in the list above to the repo, and then we can change them later if we like.
