### ISSUE TITLE
work on resolving warning in CI (2024-01)

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#437]
Currently we have a ton of warning being thrown in CI. The major ones are listed below from [ubuntu-latest, ci/312-dev.yaml](https://github.com/pysal/spopt/actions/runs/7515967068/job/20460520093#step:6:704).

* [x] `libpysal.weights.*` – 51100f0
  * ```
    FutureWarning: `use_index` defaults to False but will default to True in future.
    Set True/False directly to control this behavior and silence this warning
      self.w = libpysal.weights.Queen.from_dataframe(self.mexico) 
    ```
* [x] `numpy` – 697a05b
  * ```
    DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future.
    Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    ```
  * Clear internal warnings; some still thrown from [within `pyproj`](https://github.com/pysal/spopt/actions/runs/7523452876/job/20476833081?pr=439#step:6:527)
* [x] `geopandas` – ef3dfa5
  * ```
     FutureWarning: The 'unary_union' attribute is deprecated, use the 'union_all()' method instead.
     ```
  * warning still thrown, but now future-proofed.

**Comment by martinfleis** [comment]
Just a note that the first one is also coming from geopandas.

**Comment by jGaboardi** [comment]
The `weights` one is coming from inside `geopandas`? That seems odd...

**Comment by martinfleis** [comment]
Ah, no! My mistake. Geopandas has a very similar warning :D

**Comment by jGaboardi** [comment]
> Ah, no! My mistake. Geopandas has a very similar warning :D

*phew*... I thought I was going crazy.
