### ISSUE TITLE
clean root directory

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#44]
- [x] Rename `doc` to `docsrc` (also see #40)
- [x] remove `readthedocs.yml`
- [ ] other?

**Comment by jGaboardi** [comment]
**Follow-up from the [2020-05 dev meeting](https://hackmd.io/AnnMZhUARq6qnizL8ElWoA?both#PySAL-Website-Update-sjsrey)**

@knaaptime Shall we have a `figs/` directory to house images for `README.md` or source them from `docs/_static/images/`?

**Comment by jGaboardi** [comment]
See also #41

**Comment by knaaptime** [comment]
good question. Also pinging @darribas, since this is related to the standardized formatting we want to adopt for the book. I dont know that i have a strong preference, so long as we canonize one location

**Comment by jGaboardi** [comment]
@knaaptime I'm going with `docs/_static/images/` for now. We can change later if needed.
