### ISSUE TITLE
next release - summer 2024

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#455]
@gegen07 @ljwolf 

I'd like to cut a release prior to the summer meta release of PySAL. I'd go with `v0.6.1` but wanted to ping yall in there are differing opinions.

#### Steps

* [x] cut at least one `rc` to ensure release & doc actions still work properly -- [`v0.6.1rc1`](https://github.com/pysal/spopt/releases/tag/v0.6.1rc1)
* [x] cut actual release -- [`v0.6.1`](https://github.com/pysal/spopt/releases/tag/v0.6.1)

**Comment by gegen07** [comment]
LGTM!

**Comment by jGaboardi** [comment]
There is a some [problem with the upload to PyPI](https://github.com/pysal/spopt/actions/runs/9598313190).

* the [`v0.6.1`](https://github.com/pysal/spopt/actions/runs/9598313190/job/26469293383#step:3:76) tag is clearly there,
* but then for some reason [`v0.6.1rc1`](https://github.com/pysal/spopt/actions/runs/9598313190/job/26469293383#step:7:21) is being picked up in the next step...

Any thoughts?

cc @martinfleis @knaaptime

**Comment by martinfleis** [comment]
![Screenshot 2024-06-20 at 15 35 08](https://github.com/pysal/spopt/assets/36797143/033b085c-2650-4b5c-b197-18bb8440e4db)

Can't assign tags to the same commit. I always create empty commit prior tagging.

```
git commit --allow-empty -m 'RLS: v0.6.1'
git tag -a v0.6.1
```

**Comment by jGaboardi** [comment]
@martinfleis NICE! Thanks for reminding! I remember this happened previously. Maybe it will stick in my memory next time.

**Comment by jGaboardi** [comment]
confirmed up [on PyPI](https://pypi.org/project/spopt/)
