### ISSUE TITLE
setup.py and .travis.yml need maintainer information

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#5]
- `setup.py` needs to be updated to conform with the [`submodule_template`](https://github.com/pysal/submodule_template/blob/master/setup.py)

- Maintainer info in `setup.py` needs updating
   - Currently:
       - `maintainer="PySAL Developers"`
       - `maintainer_email='pysal-dev@googlegroups.com'`
    - Should be updated once the new maintainers are decided for `region`.

**Comment by knaaptime** [comment]
we also have some slightly different [travis conventions](https://github.com/pysal/pysal/blob/master/.travis.yml) suggested by @ocefpaf, so we should adopt those also

**Comment by jGaboardi** [comment]
I'll submit a fresh PR to implement those.

**Comment by knaaptime** [comment]
are we good to close this, or should we wait for resolution on an email address?

**Comment by jGaboardi** [comment]
We should leave it open for the time being until we have an email address up in there. It's currently blank. @sjsrey, was it ever decided who was going to be the primary maintainer of `spopt`?

**Comment by jGaboardi** [comment]
Decided on @jGaboardi with @xf37 @sjsrey during the 2020-05-08 `spopt` call.
