### ISSUE TITLE
Installing for Google Collab 

### ISSUE THREAD

**Issue by schandler88** [pysal/spopt#69]
Hi! I'm using google's Colab but struggling to install spopt, specifically looking to use MaxPHeuristic. 

Any ideas why I'm unable to install spopt in Colab?

**Comment by jGaboardi** [comment]
I have never used Colab, so I won't be any help there, but what error message are you getting? Also please include your system information. And Python version, package versions (`scipy`, `numpy`, `geopandas`, etc.).

**Comment by schandler88** [comment]
As of April 2020, Colab uses Python 3.6.9 - Geopandas: 0.8.1 - Numpy: 1.18.5
The cool thing about colab is it doesn't run locally, so it should run with the latest and greatest seeing how you need to re-install some libraries for each notebook. 

when I run `!pip install spopt` I receive the following error: 

> ERROR: Could not find a version that satisfies the requirement spopt (from versions: none)
> ERROR: No matching distribution found for spopt

or `from pysal import spopt` I get:

> ImportError                               Traceback (most recent call last)
> <ipython-input-5-ab9057573e78> in <module>()
> ----> 1 from pysal import spopt
> 
> ImportError: cannot import name 'spopt'
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.

![Screen Shot 2020-11-12 at 12 11 50 PM](https://user-images.githubusercontent.com/22751696/98972991-2ca22f00-24e1-11eb-82b1-7de34bb54a0a.png)

I was able to install pysal's region by !pip install `git+https://github.com/pysal/region.git#egg=region` but not sure what to do from here to get MaxPHeuristic

Thank you for responding so quickly!

**Comment by knaaptime** [comment]
we havent realeased spopt on pypi yet, so you'll need to install from source

**Comment by jGaboardi** [comment]
> I was able to install pysal's region by !pip install git+https://github.com/pysal/region.git#egg=region but not sure what to do from here to get MaxPHeuristic

Looks like you installed `region`, not `spopt`.

**Comment by knaaptime** [comment]
if you're after max-p, you might want to check out [geosnap](https://github.com/spatialucr/geosnap/)'s [cluster_spatial](https://spatialucr.github.io/geosnap/generated/geosnap.analyze.cluster_spatial.html#geosnap.analyze.cluster_spatial) method which wraps the clusterers from `region`

**Comment by jGaboardi** [comment]
@schandler88 `spopt` is now up on [PyPI](https://pypi.org/project/spopt/) and will soon be available via `conda-forge`. I'll go ahead and close for now, but feel free to reopen if you run into trouble again.
