### ISSUE TITLE
input is not sanitised before it is used

### ISSUE THREAD

**Issue by ljwolf** [pysal/spopt#7]
I'm not running checks on the input, nor casting input to an array in the `Spanning_Tree` clusterer.

**Comment by jGaboardi** [comment]
@ljwolf Any update on this?

**Comment by ljwolf** [comment]
Nope. A simple "asarray" would do it I think.

**Comment by jGaboardi** [comment]
Is this from within [`skater.Skater()`](https://github.com/pysal/spopt/blob/42520cc53d10c14a61ac8ba79bdd45e080281775/spopt/region/skater.py#L438-L439)? I can't find anything defined as `Spanning_Tree` with `spopt`. If it is, doesn't the `.values` attribute automatically convert to a `numpy.array`?:
```python
X = data[self.attrs_name].values
model = SpanningForest(**self.spanning_forest_kwds)
```

**Comment by jGaboardi** [comment]
@sjsrey Any thoughts here? This seems like it would be an easy issue to close out, but I'm not sure where it was happening before.

**Comment by ljwolf** [comment]
Using the .values is fine! I think I filed this before the new api

**Comment by jGaboardi** [comment]
OK, awesome. Thanks for the feedback @ljwolf! I'll go ahead and close this then. Also, happy holidays!
