### ISSUE TITLE
Issues caused by GitHub Actions: Deprecating set-env and add-path commands

### ISSUE THREAD

**Issue by xf37** [pysal/spopt#70]
There is an ongoing issue leading to the following errors.
Error: Unable to process command '::add-path::/usr/share/miniconda3/condabin' successfully.
Error: Unable to process command '::set-env name=CONDA::/usr/share/miniconda3' successfully.
Error: The `add-path` command is disabled.
Error: The `set-env` command is disabled.

**Comment by xf37** [comment]
GitHub Actions deprecate set-env and add-path commands.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/.

**Comment by jGaboardi** [comment]
See also [this commit](https://github.com/pysal/libpysal/commit/33b73590fe3e7eefd461e381d61df9ded607be34)
