### ISSUE TITLE
Python error (Ubuntu): Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xf37** [pysal/spopt#76]
The failure is cropping up in [this PR](https://github.com/pysal/spopt/pull/75/checks?check_run_id=1476836423#step:8:12) and [other PR](https://github.com/pysal/spopt/pull/74/checks?check_run_id=1476859662#step:8:118).

**Comment by jGaboardi** [comment]
Both associated PRs are now merged. Closing.
