### ISSUE TITLE
add spenc to requirements.txt

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spopt#80]
`spenc` is not defined in `requirements.txt` but is used in [`spopt/region/spenc.py`](https://github.com/pysal/spopt/blob/main/spopt/region/spenc.py).

**Comment by knaaptime** [comment]
i think we want to re-implement spenc here instead of using the standalone package

**Comment by jGaboardi** [comment]
> i think we want to re-implement spenc here instead of using the standalone package

So should I close this here for now?

**Comment by knaaptime** [comment]
yeah, but we should have an issue for integrating spenc instead

**Comment by knaaptime** [comment]
closing in favor of #81
